# Site settings
title: "Gregory Spangenberg"
description: "A resume about Greg"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Gregory Spangenberg"
resume_title:                   "Computer Vision Researcher and PhD Candidate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "gspangen@westerneng.ca"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 519-476-0307"
resume_contact_address:         ""

resume_header_contact_info:     "London, Ontario, Canada • gspangen@westerneng.ca"
display_header_contact_info:    "true"

resume_header_intro: "<p> Current research is focused on developing machine learning models for automated shoulder arthroplasty planning and post-operative surgical complication prediction with only 3D medical imaging. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/gregspangenberg"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/gregory-spangenberg-6b8645152/"
  # resume_instagram_url:         "https://www.instagram.com/gregspangenberg/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_pdf_url:                 "images/cv.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

